# Generated by Django 3.0.8 on 2020-08-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20200730_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to='profilepics'),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
